### ISSUE TITLE
Unable to get screenshots to appear in GH Actions Check

### ISSUE THREAD

**Issue by BaseInfinity** [edunad/actions-image#4]
Looks like I am able to get this step to successful pass and create a check with screenshots but the problem is the screenshots appear to be broken:
![Screen Shot 2022-07-20 at 1 44 26 PM](https://user-images.githubusercontent.com/1424113/180078604-93cb9c65-97fd-4f96-8374-7a21ac0fe371.png)

When clicking on an Image I get a `Cannot proxy the given URL` error.

Is this expected? When looking at the output, it appears successful:
![Screen Shot 2022-07-20 at 1 44 10 PM](https://user-images.githubusercontent.com/1424113/180079063-69661a45-5aed-4182-92c7-e352a498554b.png)

Thanks! 

Not sure if it impacts the above but we forked the repo at `v1.0.1`

**Comment by edunad** [comment]
Hi! It seems 0x0.st recently started blocking CI/CD, as now it's stated on their Terms of Service: 
![](https://i.rawr.dev/BXceVvR4wN.png)

Blocking all github / gitlab requests I'll look into uploading the pictures to github directly instead of them being hosted.

**Comment by BaseInfinity** [comment]
That would be awesome!

**Comment by ftzi** [comment]
Any updates, @edunad ?

**Comment by edunad** [comment]
@SrBrahma sorry for the delay, I tried my best to find a way to upload it to GitHub directly, but it seems there is no API yet. 

Managed to find a replacement `https://litterbox.catbox.moe/`. I've released a new version with that as the default
