### ISSUE TITLE
Images array was larger than 65535 bytes

### ISSUE THREAD

**Issue by easygolabs** [edunad/actions-image#6]
**Error:** 

The size of all the files that were uploaded is 1397741 bytes. And the error occurs:

    Validation Failed: {"resource":"CheckRun","code":"custom","field":"images","message":"images array was larger than 65535 bytes"}

**Expected behavior:**

No error. Is there any way to increase the limit in case a lot of screenshots?

**Comment by edunad** [comment]
Seems to be a github api limit on actions, you can try optimizing the images after they are created using `pngquant` / `mozjpeg` or reducing their width / height
