### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by KenwoodFox** [edunad/actions-image#7]
```
Run edunad/actions-image@v2.0.0
  with:
    path: UnnamedClockProject-3D_top.png
    GITHUB_TOKEN: ***
    title: PCB
    uploadHost: https://litterbox.catbox.moe/
    annotationTag: [--]
    annotationLevel: notice
Error: Failed to upload images
Error: Cannot read properties of undefined (reading 'map')
```

It might just be something I've misconfigured...
https://github.com/KenwoodFox/UnnamedClockProject/blob/22053a8d6d00088100b44c9347cd59f84a6e46e9/.github/workflows/hardware_workflow.yml#L53-L69

But even if it is, i don't understand what map its talking about, the error should be more descriptive of what I did wrong? Thanks and lmk!

**Comment by edunad** [comment]
Hi! thanks for the bug report, can you try using `https://litterbox.catbox.moe/resources/internals/api.php` on the `uploadHost` (or remove it so it uses the default)?

**Comment by KenwoodFox** [comment]
> Hi! thanks for the bug report, can you try using `https://litterbox.catbox.moe/resources/internals/api.php` on the `uploadHost` (or remove it so it uses the default)?

Thanks! That.. kinda worked? it didn't error out! but it also didn't comment the image like i was expecting, instead it just sort-of errored out like this: 
![image](https://github.com/edunad/actions-image/assets/31870999/086a83d7-15af-47c4-80e9-5aec35f4971f)

Let me know what might be helpful to try next!

**Comment by edunad** [comment]
I'll update the default url #8 , that is weird that the image is not attached, is it a big image? Is there any sort of link?

**Comment by edunad** [comment]
Can you use `v2.0.2` and check again :D?

**Comment by KenwoodFox** [comment]
Hmm, it still seems to have not included an image, it certainly didn't put it in the pull request comment and if i click on the annotation it just looks like this 
![image](https://github.com/edunad/actions-image/assets/31870999/16cf3fe7-db27-4dc1-b4c3-84b53998c73a)

The URL it gave me is this: https://camo.githubusercontent.com/fac3beb61110da650284910205f309067ef2d8b3933fdf81f725bbd6020f9534/4e6f2072657175657374207479706520676976656e2e

if i go there i see this
![image](https://github.com/edunad/actions-image/assets/31870999/9d39b5ad-3ecc-4794-bf8b-611ccb41a1fc)

The image is pretty small, do you have maybe a test-repo where this is setup and working?

**Comment by edunad** [comment]
I'll setup a public one, is it possible to have the image

**Comment by edunad** [comment]
Should be fixed now, there was some issues with the litterbox api
https://github.com/edunad/actions-image/actions/runs/6233546335/job/16918995083

Can you try v2.0.3

**Comment by KenwoodFox** [comment]
That looks like it did it, thanks so much!
